# Generated by Django 5.2.6 on 2025-11-18 21:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.CharField(max_length=20, unique=True, verbose_name='学号或工号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('college', models.CharField(max_length=100, verbose_name='学院')),
                ('user_type', models.IntegerField(choices=[(0, '学生'), (1, '老师'), (2, '超级管理员')], default=0, verbose_name='用户类型')),
                ('grade', models.CharField(blank=True, max_length=20, null=True, verbose_name='年级')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('class_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='班级')),
                ('has_postgraduate_qualification', models.BooleanField(default=False, verbose_name='是否有保研资格')),
                ('is_applying_postgraduate', models.BooleanField(default=False, verbose_name='是否申请保研')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='职称')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
