# Generated by Django 5.2.6 on 2025-11-18 21:59

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('first_review_comment', models.TextField(blank=True, null=True, verbose_name='一审意见')),
                ('first_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='一审时间')),
                ('review_status', models.IntegerField(choices=[(0, '草稿'), (1, '待审核'), (2, '审核通过'), (3, '审核不通过')], default=0, verbose_name='审核状态')),
                ('result', models.BooleanField(blank=True, null=True, verbose_name='审核结果')),
                ('Real_Score', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='加分')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Type', models.IntegerField(choices=[(0, '学术竞赛成绩'), (1, '创新训练成绩'), (2, '学术研究成绩'), (3, '荣誉称号成绩'), (4, '社会工作成绩'), (5, '志愿服务成绩'), (6, '国际实习成绩'), (7, '参军入伍成绩'), (8, '体育项目成绩')], verbose_name='申请类型')),
                ('Title', models.CharField(help_text='例如：论文标题、竞赛名称等', max_length=200, verbose_name='申请标题')),
                ('ApplyScore', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='申请分数')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='详细描述')),
                ('Feedback', models.CharField(max_length=200, verbose_name='反馈')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='扩展数据')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('UploadTime', models.BigIntegerField(default=0, help_text='毫秒时间戳', verbose_name='上传时间戳')),
                ('ModifyTime', models.BigIntegerField(default=0, help_text='毫秒时间戳', verbose_name='修改时间戳')),
            ],
            options={
                'verbose_name': '统一申请',
                'verbose_name_plural': '统一申请',
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='附件名称')),
                ('file', models.FileField(blank=True, null=True, upload_to='applications/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx'])], verbose_name='附件文件')),
                ('file_hash', models.CharField(blank=True, help_text='文件的SHA-256哈希值，用于文件去重和完整性验证', max_length=64, null=True, verbose_name='文件哈希值')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'db_table': 'attachment',
            },
        ),
    ]
