# Generated by Django 5.2.6 on 2025-11-18 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='first_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_reviewed_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='一审老师'),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核老师'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['file_hash'], name='attachment_file_ha_57d320_idx'),
        ),
        migrations.AddField(
            model_name='application',
            name='Attachments',
            field=models.ManyToManyField(blank=True, to='application.attachment', verbose_name='附件列表'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'review_status'], name='application_user_id_e964bc_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['review_status', 'Type', 'UploadTime'], name='application_review__818026_idx'),
        ),
    ]
