# Generated by Django 5.2.6 on 2025-11-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attachments_array',
            field=models.JSONField(blank=True, default=list, help_text='存储附件ID的字符串数组，用于快速访问', verbose_name='附件ID数组'),
        ),
    ]
