# Generated by Django 5.2.6 on 2025-11-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_attachments_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_hash',
            field=models.CharField(blank=True, help_text='文件的SHA-256哈希值，用于文件完整性验证', max_length=64, null=True, verbose_name='文件哈希值'),
        ),
    ]
